--INSERT INTO Instructor (id, name) VALUES (1, "Amit");
--INSERT INTO Instructor (id, name) VALUES (2, "Anjaney");
--INSERT INTO Instructor (id, name) VALUES (3, "Nishant");
--INSERT INTO Instructor (id, name) VALUES (4, "Rashmi");
--INSERT INTO Instructor (id, name) VALUES (5, "Rohit");